[env]
TERM = "xterm-256color"
LC_ALL = "en_US.UTF-8"

[window]
startup_mode = "Maximized"

[scrolling]
history = 100000

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
size = 13

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#000000"

[keyboard]
bindings = [
  { key = "Enter", mods = "Command", action = "ToggleFullScreen" },
  { key = "Tab", mods = "Control", action = "SelectNextTab" },
  { key = "Tab", mods = "Control|Shift", action = "SelectPreviousTab" },
]

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["-u"]
